version: '3.8'

services:
  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - kafka-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - kafka-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kafka-net

  etl_consumer:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: etl_consumer
    environment:
      IN_DOCKER: "1"
      KAFKA_BROKER: kafka:9092  # Usa el Kafka del producer
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      kafka-net:
        external:
          name: data-engineering-educational-project_kafka-net
        default:
          driver: bridge

    services:
      etl_consumer:
        networks:
        - default      
        - kafka-net

    restart: unless-stopped
    depends_on:
      - mongo
      - redis
      - postgres

networks:
  kafka-net:
    external: true  # Usar la red externa del producer

volumes:
  mongo_data:
  pgdata: