version: "3.9"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MYSQL_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/data/db

volumes:
  mysql_data:
