services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "39092:29092"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl_consumer:
    build: .
    depends_on:
      - kafka
      - mongo
      - redis
      - postgres
    environment:
      - IN_DOCKER=1
      - KAFKA_BROKER=kafka:29092
      - KAFKA_TOPIC=probando
      - KAFKA_GROUP_ID=etl-consumer-group-test1
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=etl_db
      - MONGO_COLLECTION=raw_data
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_DB=etl_db
      - POSTGRES_USER=etl_user
      - POSTGRES_PASSWORD=etl_pass
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    command: python -m kafka_consumer.consumer
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mongo_data:
  pgdata:
