FROM apache/nifi:1.28.1


USER root
RUN apt-get update && apt-get install -y wget
RUN mkdir -p /opt/nifi/nifi-current/lib/
RUN wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.20/mysql-connector-java-8.0.20.jar




USER nifi
