services:
  nifi:
    image: apache/nifi:1.28.1
    container_name: nifi
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=8080
    restart: unless-stopped
    
volumes:
  nifi_data:
