version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_HEAP_INITIAL=512m
      - NIFI_HEAP_MAX=1g
    volumes:
      - nifi_data:/opt/nifi/nifi-current/data
    restart: unless-stopped

volumes:
  nifi_data:
